package.json
src/critical.js

Use os.tmpdir() folder for temporary css

---

test/fixture/adaptive-final.css
test/fixture/adaptive.html
test/test.js

This was not caught during the initial code review because there is a
bug in the test suite: see #67

Fix multi test

---

lib/fileHelper.js
test/02-generate.js
test/fixtures/generate-default-querystring.html

Turns out fs doesn’t particularly enjoy having a query string in a file name and throws a “file not found” error. But fear not! This patch is here to the rescue!
But seriously, though…
`<link rel="stylesheet" href="/main.css?v=1445367009869"/>` does not work and this patch should fix it. Or at least it works for me!

Fix local files query string ENOENT exception.

---

lib/gc.js

log error on uncaughtException

---

test/02-generate.js

Adapt tests to current server response.

Fix test failures.

---

README.md

Code example was missing a comma. Added.

Added missing comma to the sample code

---

README.md
cli.js
lib/core.js
lib/file-helper.js
test/02-generate.js
test/expected/generate-adaptive-useragent.css
test/fixtures/useragent/generate-default-useragent.html
test/fixtures/useragent/styles/bootstrap.css
test/fixtures/useragent/styles/main.css

Closes #303 
I included the option on the lib and cli, also added a test for it.
I'm hoping it's following the overall style and it's a smooth review :smiley:

Add user agent option

---

test/03-cli.js

/CC @addyosmani @bezoerb 
Locally on Windows I get `103 passing (1m)`

Fix tests on Windows.

---

cli.js
index.js
lib/core.js
lib/file-helper.js
lib/gc.js
lib/vinyl-remote.js
test/00-lib.js
test/01-module.js
test/02-generate.js
test/03-cli.js
test/04-streams.js
test/helper/testhelper.js

Requires #330  to be merged first.

Use ES6 more

---

index.js
package.json
test/array.test.js
test/blackbox.test.js
test/cli.test.js
test/config.test.js
test/core.test.js
test/file.test.js
test/helper/index.js
test/helper/testhelper.js
test/index.test.js

@bezoerb: There are some remaining failures, so feel free to push to this branch.

Lint everything

---

.travis.yml

Travis CI: remove libnss3 dep.

---

README.md

Should be faster and also we are more consistent.

README.md: use shields.io for all badges.

---

src/core.js
src/file.js
test/blackbox.test.js
test/file.test.js

* use template literals
* use arrow function

Use ES6+ more.

---

package-lock.json
package.json
src/array.js
src/core.js
src/file.js
test/array.test.js
test/file.test.js

@bezoerb please review this. There's also one error I'm not sure how to fix, so feel free to push here.

Update xo to v0.25.3.

---

package.json

package.json: Node.js >= 8.10.0 is needed.

---

package-lock.json
package.json

* eslint-plugin-prettier
* mockery

Remove unused devDependencies.

---

src/core.js
test/blackbox.test.js
test/fixtures/issue-415.html
test/fixtures/styles/issue-415.css

fix: sorts dimensions so we don't mess up the css order (#415)

---

package-lock.json
package.json
src/file.js
test/blackbox.test.js
test/file.test.js
test/fixtures/generate-adaptive-base64.html
test/fixtures/generate-adaptive-inline.html
test/helper/index.js

Process Inline styles #463
Handle data-uri stylesheets #496

Adds support for inline styles & data-uris

---

src/file.js
test/file.test.js
test/fixtures/media-attr.html
test/fixtures/styles/media-attr.css

Adds support for media attribute on link elements

---

src/file.js
test/blackbox.test.js
test/cli.test.js
test/expected/issue-566.css
test/file.test.js
test/fixtures/folder/styles/issue-566.css
test/fixtures/issue-566.html

Adds support for html base tag

---

package.json

adds file & errors to exports
