- README.md
- index.js
- test/fixture/styles/critical-adaptive.css
- test/test.js
This is useful when you want to deliver multiple dimensions
of critical css. Take for instance when your site has different elements
visible at different resolutions. Prior to this work you were limited to
multiple critical passes and inclusions or simply picking one
resolution.
I am glad you asked yourself that. Since we use
clean-css we can intelligently merge the multiple resolution snapshots
making for smaller and better multi snapshot rule generation.
While working on a website I noticed that we were getting a flash of
styles after the normal stylesheet was loaded. This was not so bad on a
computer screen (since that was the dimension that we targeted) however
when on a phone it was quite a jarring experience.
-------
Thanks for this great tool and great work keeping this library …
> Add support for multi-dimension critical css.

- README.md
- index.js
- test/02-generate.js
- test/expected/path-prefix.css
- test/fixtures/path-prefix.html
- test/fixtures/styles/path-prefix.css
Defaults to "/" but does not add "/" automatically since this would prevent people from using this to set paths to be relative (if you specify pathPrefix to "" it will make your paths relative paths instead of absolute).
Fixes #51
> Allows pathPrefix to be set through options.

- cli.js
- test/05-cli.js
For CLI usage it's much more suitable to toggle `generate`and `generateInline` with one option instead of passing `htmlTarget` and `styleTarget` 
`critical source.html > critical.css`
`critical source.html --inline > dest.html`
> deprecated htmltarget & styletarget for CLI and introduced --inline

- index.js
Returning the error does nothing, it needs to be given to the callback and thus emitted in the stream.
Now, errors from critical will crash the stream and gulp will output them to the console (previously, it just exited).
> Stream: Actually Emit Critical's Errors

- lib/fileHelper.js
- test/02-generate.js
- test/fixtures/404-css.html
Hey guys, two changes here.
The first is straightforward — promises should be rejected with an Error and not a String (this was yielding warnings).
Secondly, I think it's best to ignore 404 responses as well as 403. My main reason for doing this is that we're using remote critical generation (via URL, e.g. `/about`), but the pages referenced include the actual critical CSS that is about to be generated (e.g. `/css/about-critical.css`). Of course, it's not yet generated (since that's what we're doing) and it errors.
However, I also think that generation shouldn't stop just because one resource can't be found. A different solution would be including an option for this on initialisation.
Let me know what you think.
> Ignore 404 requests, reject promise with Error not String

- lib/gc.js
- test/02-generate.js
- test/03-inline.js
- test/04-generateInline.js
- test/05-cli.js
- test/06-streams.js
In addition to issue #133, this removes the uncaughtException handler altogether. Errors will cause the process to exit (with code 1 instead of 99), triggering the exit event which, in turn, triggers a cleanup.
> remove uncaughtException listener and related functions

- package.json
💁  This change bumps the version of the `node-cli` package to version 1.0.1. This resolves a security issue.
```
$ nsp check
(+) 1 vulnerabilities found
┌───────────────┬───────────────────────────────────────────────────────┐
│               │ Arbitrary File Write                                  │
├───────────────┼───────────────────────────────────────────────────────┤
│ Name          │ cli                                                   │
├───────────────┼───────────────────────────────────────────────────────┤
│ Installed     │ 1.0.0                                                 │
├───────────────┼───────────────────────────────────────────────────────┤
│ Vulnerable    │ All                                                   │ …
```
> Bump cli package to v1.0.1

- README.md
- lib/core.js
- test/02-generate.js
Critical can now process CSS files passed to the library as an array of Vinyl file objects in `opts.css`, so they do not need to be written to disk before processing.
This consists of two very small changes.
1: `core.vinylize` now checks if parameter `filepath` is already a Vinyl file before attempting to make a Vinyl file out of it.  If `filepath` is already a Vinyl file, just return it.
2: `core.appendStylesheets` now checks if `opts.css` is an array before converting it to an array. Previously, it checked if `opts.css` was a string.
I was going to update `README.md` to reflect that `opts.css` could be a Vinyl file, an array of Vinyl files, a string, or an array of strings, but it seems `opts.css` is not documented there at all. I can add it to the table, but I didn't know if this was …
> Support for passing CSS files as Vinyl objects.

- package-lock.json
- package.json
- yarn.lock
This upgrades Penthouse in order to avoid a dependency on the "CSS" package directly from GitHub.
See https://github.com/pocketjoso/penthouse/issues/162
> Upgrade Penthouse

- README.md
The vertical bar '|' has special meaning in markdown within lists. To ensure correct parsing, whenever it appears in a list, it has to be replaced by its HTML character entity reference (&#<span>124;</span>).
> Replace '|' with its HTML character entity reference

- README.md
Hi,
gulp-util is deprecated and should be replaced by respective packages. in this case use logging functionality from fancy-log.
Cheers
midzer
> replace gutil by fancy-log

- src/config.js
`user` and `pass` options were missing when validating the schema.
This tiny PR adds them back.
> Add missing user and pass options

- README.md
Just a nit; The default value for the target viewpoint width and height were interchanged in the README.
> Fix viewpoint width and height default values in README

- src/file.js
Fixes #373
I noticed there's a lovely helper that checks constructor for if `isVinyl`
https://github.com/addyosmani/critical/blob/cd3015345ccc0c693f85371627673b883485bb2d/src/file.js#L109
It appears however there are two places that were missed when adding use of this helper which can cause the stream to error out with an error when using Gulp 3:
```
Parameter file needs to be a vinyl object
````
> Fix Support for Gulp 3 Streams

- test/blackbox.test.js
BTW we might not even need to do the `path.join` calls since we have `process.chdir(path.resolve(__dirname));` but that's for another time
> blackbox.test.js: move fixtures path to a variable.

- cli.js
- index.js
- src/array.js
- src/config.js
- src/core.js
- src/errors.js
- src/file.js
- test/array.test.js
- test/blackbox.test.js
- test/cli.test.js
- test/config.test.js
- test/core.test.js
- test/file.test.js
- test/helper/index.js
- test/index.test.js
They are still needed.
@bezoerb: we need to enforce this in xo somehow, but I recall having trouble with it because xo prefers modules. We could live without a rule, but ideally, we should enforce it until the time has come to fully switch to mjs.
http://imaginativethinking.ca/what-the-heck-is-node-modules-strict-by-default/
> Add back "use strict" statements.

- README.md
* use ES6
* remove trailing commas
* add a missing comma in a snippet
* break lines
* add a Windows standard input example using `type`
* link to the license
I'll wait until we finish the latest 1.x version so that we link to the branch and not the tag.
> README.md: various tweaks.

- test/02-generate.js
This is also done on master and since AppVeyor consistently fails, it seems it's the only solution...
> Skip the PAGE_UNLOADED_DURING_EXECUTION` tests.

- cli.js
- index.js
- lib/core.js
- lib/file-helper.js
- lib/gc.js
This should be slightly faster
Saves ~50ms from the module load time.
@bezoerb after we merge this please release a new 1.x version. We can look into #425 later
> 1.x: use destructuring when importing lodash

- README.md
Since `timeout` has been removed as it is saying in [CHANGELOG](https://github.com/addyosmani/critical/blob/master/CHANGELOG.md), should be removed from README as well
> Remove timeout option from example configuration

- src/file.js
Fixes https://github.com/addyosmani/critical/issues/469.
Do not mutate the `request.method` when checking if a file exists to avoid future unwanted HEAD requests (which expects a response body).
> Do not mutate request.method when checking file exists

- README.md
> Correct the parameters in callback example

- cli.js
- src/file.js
- test/file.test.js
Multiple --css flags were lost in v2.0, this restores the possibility of multiple --css flags
Fixes https://github.com/addyosmani/critical/issues/514
Thanks to @josenobile for his work on this in #515
> Allow multiple --css flags in cli (fixes #514)
